spring:
  redis:
    port: 6379
    client-type: jedis
    host: 192.168.74.130
    database: 0
    timeout: 1800000
    pool:
     max-active: 20
     max-wait: -1
     min-idle: 0


  datasource:
    url: jdbc:mysql:///test
    username: root
    password: 585346
    driver-class-name: com.mysql.jdbc.Driver